version: "3.9"

services:
  postgres:
    image: postgres:16.2
    container_name: desafio_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_USERNAME}   # Aqui você pode usar o nome do banco como o mesmo usuário ou criar outro nome se quiser
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ..
    container_name: desafio_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DATABASE_USERNAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD_APP: ${EMAIL_PASSWORD_APP}
      SECRET_KEY_IN_BASE_64: ${SECRET_KEY_IN_BASE_64}

volumes:
  postgres_data:
